## Problem 4 (*optional*) - Parsing daily temperatures

**This is an optional task for those who want more practice.**

This problem is more challenging as we provide only minimal instructions for completing the given tasks. You will need to search through the pandas documentation (and other resources) for help. We will cover data aggregation in more detail during Lesson 6, so this is a good opportunity to get a head start for next week!

In this problem, the aim is to aggregate the hourly temperature data for Helsinki Kumpula and Rovaniemi weather stations to the daily level. Currently, there are (at most) 3 measurements per hour in the data as you can see from the `YR--MODAHRMN` column (Year-Month-Day-Hour-Minute in Greenwich Mean Time (GMT):

```
    USAF  YR--MODAHRMN  TEMP  MAX  MIN  Celsius
0  28450  201705010000  31.0  NaN  NaN       -1
1  28450  201705010020  30.0  NaN  NaN       -1
2  28450  201705010050  30.0  NaN  NaN       -1
3  28450  201705010100  31.0  NaN  NaN       -1
4  28450  201705010120  30.0  NaN  NaN       -1
```

The output should contain mean, max, and min Celsius temperatures for each day (for example, one mean temperature value for the 1st of May and so on).

### What to do

- Your task is to summarize the information for each day by aggregating (grouping) the DataFrame.
- The output should be a new DataFrame where you have calculated the mean, max, and min Celsius temperatures for each day separately based on hourly values.
- Repeat the task for the two data sets you created in Problem 2 (May-August temperatures from Rovaniemi and Kumpula).

Don't forget to:

- Include useful comments in your code
- Push your solution to GitHub

### Hint

You can find help from the [Pandas Official documentation](https://pandas.pydata.org/pandas-docs/stable/) and Google. Don't hestiate to ask for tips in Discord!

In [1]:
import pandas as pd

In [2]:
kumpula_may = pd.read_csv("Kumpula_temps_May_Aug_2017.csv")
rovaniemi_may = pd.read_csv("Rovaniemi_temps_May_Aug_2017.csv")

In [15]:
kumpula_may["date"] = kumpula_may["YR--MODAHRMN"].astype(str).str[:8]
rovaniemi_may["date"] = rovaniemi_may["YR--MODAHRMN"].astype(str).str[:8]
kumpula_may

      Unnamed: 0   USAF  YR--MODAHRMN  TEMP  MAX  MIN  Celsius      date
0           8770  29980  201705010000  37.0  NaN  NaN        3  20170501
1           8771  29980  201705010100  37.0  NaN  NaN        3  20170501
2           8772  29980  201705010200  37.0  NaN  NaN        3  20170501
3           8773  29980  201705010300  37.0  NaN  NaN        3  20170501
4           8774  29980  201705010400  39.0  NaN  NaN        4  20170501
...          ...    ...           ...   ...  ...  ...      ...       ...
2919       11689  29980  201708311900  64.0  NaN  NaN       18  20170831
2920       11690  29980  201708312000  64.0  NaN  NaN       18  20170831
2921       11691  29980  201708312100  64.0  NaN  NaN       18  20170831
2922       11692  29980  201708312200  64.0  NaN  NaN       18  20170831
2923       11693  29980  201708312300  64.0  NaN  NaN       18  20170831

[2924 rows x 8 columns]

In [19]:
daily_summary_kumpula = kumpula_may.groupby("date")["Celsius"].agg(["mean", "max", "min"]).reset_index()
daily_summary_kumpula

         date       mean  max  min
0    20170501   7.625000   12    3
1    20170502   9.750000   16    2
2    20170503   9.208333   13    4
3    20170504   6.666667   11    3
4    20170505  10.250000   17    2
..        ...        ...  ...  ...
118  20170827  10.625000   14    6
119  20170828  11.826087   16    9
120  20170829  14.500000   17    8
121  20170830  16.833333   19   15
122  20170831  17.250000   19   16

[123 rows x 4 columns]

In [21]:
daily_summary_rovaniemi = rovaniemi_may.groupby("date")["Celsius"].agg(["mean", "max", "min"]).reset_index()
daily_summary_rovaniemi

         date       mean   max  min
0    20170501   2.180556   7.0 -1.0
1    20170502   3.402778   7.0  1.0
2    20170503   2.112676   4.0 -1.0
3    20170504   4.388889   9.0 -1.0
4    20170505   6.916667  12.0  1.0
..        ...        ...   ...  ...
118  20170827   7.690141  10.0  5.0
119  20170828   9.138889  13.0  3.0
120  20170829  10.722222  12.0  8.0
121  20170830  11.291667  14.0  9.0
122  20170831  12.000000  17.0  8.0

[123 rows x 4 columns]